In [1]:
import yfinance as yf

ModuleNotFoundError: No module named 'yfinance'

In [2]:
pip install yfinance
pip install stas

Collecting yfinance
  Downloading yfinance-0.2.18-py2.py3-none-any.whl (60 kB)
     -------------------------------------- 60.3/60.3 kB 228.7 kB/s eta 0:00:00
Requirement already satisfied: appdirs>=1.4.4 in c:\users\gupil\anaconda3\lib\site-packages (from yfinance) (1.4.4)
Collecting frozendict>=2.3.4
  Downloading frozendict-2.3.8-cp310-cp310-win_amd64.whl (35 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\gupil\anaconda3\lib\site-packages (from yfinance) (4.11.1)
Requirement already satisfied: requests>=2.26 in c:\users\gupil\anaconda3\lib\site-packages (from yfinance) (2.28.1)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: numpy>=1.16.5 in c:\users\gupil\anaconda3\lib\site-packages (from yfinance) (1.23.5)
Requirement already satisfied: lxml>=4.9.1 in c:\users\gupil\anaconda3\lib\site-packages (from yfinance) (4.9.1)
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     -------------------------------------- 112.2/112.2 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2022.5 in c:\users\gupil\anaconda3\lib\site-packages (from yfinance) (2022.7)
Requirement already satisfied: pandas>=1.3.0 in c:\users\gupil\anaconda3\lib\site-packages (from yfinance) (1.5.3)
Requirement already satisfied: cryptography>=3.3.2 in c:\users\gupil\anaconda3\lib\site-packages (from yfinance) (39.0.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\gupil\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.2.post1)
Requirement already satisfied: cffi>=1.12 in c:\users\gupil\anaconda3\lib\site-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: six>=1.9 in c:\users\gupil\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\gupil\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\gupil\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\gupil\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gupil\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\gupil\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gupil\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: pycparser in c:\users\gupil\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)
Installing collected packages: multitasking, html5lib, frozendict, yfinance
Successfully installed frozendict-2.3.8 html5lib-1.1 multitasking-0.0.11 yfinance-0.2.18
Note: you may need to restart the kernel to use updated packages.

In [2]:
import yfinance as yf
import statistics as stat

In [3]:
apple=yf.Ticker("aapl")
apple_history=apple.history(start="2010-01-01",end="2023-05-01",interval="1d")
apple_history["High"]

Date
2010-01-04 00:00:00-05:00      6.511169
2010-01-05 00:00:00-05:00      6.544258
2010-01-06 00:00:00-05:00      6.533327
2010-01-07 00:00:00-05:00      6.435282
2010-01-08 00:00:00-05:00      6.435281
                                ...
2023-04-24 00:00:00-04:00    165.371270
2023-04-25 00:00:00-04:00    166.080278
2023-04-26 00:00:00-04:00    165.051703
2023-04-27 00:00:00-04:00    168.327170
2023-04-28 00:00:00-04:00    169.615396
Name: High, Length: 3353, dtype: float64

In [3]:
apple_highest=max(apple_history["High"])

In [4]:
print(apple_highest)

181.35625856210308

In [7]:
apple_lowest=min(apple_history["Low"])
apple_mdd=(apple_lowest-apple_highest)*100/apple_highest
print(apple_mdd)

-96.81562841931469%

In [36]:
apple_history

,Open,High,Low,Close,Volume,Dividends,Stock Splits,return,Annualized Return
Date,,,,,,,,,
2010-01-04 00:00:00-05:00,6.478687,6.511167,6.446814,6.496293,493729600,0.0,0.0,0.017606,0.000048
2010-01-05 00:00:00-05:00,6.514204,6.544256,6.473224,6.507526,601904800,0.0,0.0,-0.006678,-0.000018
2010-01-06 00:00:00-05:00,6.507525,6.533327,6.397336,6.404014,552160000,0.0,0.0,-0.103511,-0.000299
2010-01-07 00:00:00-05:00,6.427692,6.435281,6.345733,6.392176,477131200,0.0,0.0,-0.035516,-0.000099
2010-01-08 00:00:00-05:00,6.383677,6.435281,6.346037,6.434673,447610800,0.0,0.0,0.050997,0.000136
...,...,...,...,...,...,...,...,...,...
2023-04-24 00:00:00-04:00,164.772093,165.371270,163.663625,165.101639,41949600,0.0,0.0,0.329546,0.000781
2023-04-25 00:00:00-04:00,164.961829,166.080278,163.503839,163.543793,48714100,0.0,0.0,-1.418037,NaN
2023-04-26 00:00:00-04:00,162.834768,165.051703,162.575133,163.533798,45498800,0.0,0.0,0.699030,0.001453
2023-04-27 00:00:00-04:00,164.961830,168.327170,164.961830,168.177383,64902300,0.0,0.0,3.215554,0.003950
2023-04-28 00:00:00-04:00,168.257274,169.615396,167.648116,169.445618,55209200,0.0,0.0,1.188343,0.002148

In [9]:
apple_history["Open"][0]

6.47868711721336

In [10]:
apple_CR=(apple_history["Open"][-1]-apple_history["Open"][0])*100/apple_history["Open"][0]
print(apple_CR)

2497.0890575583403

In [22]:
apple_history["return"]=apple_history["Close"]-apple_history["Open"]
print(apple_history["return"])

Date
2010-01-04 00:00:00-05:00    0.017606
2010-01-05 00:00:00-05:00   -0.006678
2010-01-06 00:00:00-05:00   -0.103511
2010-01-07 00:00:00-05:00   -0.035516
2010-01-08 00:00:00-05:00    0.050997
                               ...
2023-04-24 00:00:00-04:00    0.329546
2023-04-25 00:00:00-04:00   -1.418037
2023-04-26 00:00:00-04:00    0.699030
2023-04-27 00:00:00-04:00    3.215554
2023-04-28 00:00:00-04:00    1.188343
Name: return, Length: 3353, dtype: float64

In [55]:
apple_avgreturn=stat.mean(apple_history["return"])
print(apple_avgreturn)

0.03783907739542387

In [56]:
apple_riskfree=((apple_history["Open"][0])*(1+5.25/100)**(4869/365)-apple_history["Open"][0])/4869

In [57]:
print(apple_riskfree)

0.0013026019193230023

In [58]:
apple_std=stat.stdev(apple_history["return"])
print(apple_std)

1.1478769799360022

In [59]:
apple_sharpe=(apple_avgreturn-apple_riskfree)*(252**0.5)/apple_std

In [60]:
print(apple_sharpe)

0.505279378795257

In [63]:
a=[]
i=0
while(apple_history["return"][i]):
    if(apple_history["return"][i]<0):
        a.append(apple_history["return"][i])
    i+=1   
apple_downdev=stat.stdev(a)
print(apple_downdev)

0.12990867595697567

In [65]:
apple_sortino=(apple_avgreturn-apple_riskfree)*(252**0.5)/apple_downdev
print(apple_sortino)

4.4646638346735825

In [69]:
apple_volatility=stat.stdev(apple_history["return"]*(252**0.5))
print(apple_volatility)

18.221982147639245

In [73]:
tesla=yf.Ticker("tsla")
tesla_history=tesla.history(start='2010-01-01',end='2023-05-01',interval='1d')
tesla_history

                                 Open        High         Low       Close  \
Date
2010-06-29 00:00:00-04:00    1.266667    1.666667    1.169333    1.592667
2010-06-30 00:00:00-04:00    1.719333    2.028000    1.553333    1.588667
2010-07-01 00:00:00-04:00    1.666667    1.728000    1.351333    1.464000
2010-07-02 00:00:00-04:00    1.533333    1.540000    1.247333    1.280000
2010-07-06 00:00:00-04:00    1.333333    1.333333    1.055333    1.074000
...                               ...         ...         ...         ...
2023-04-24 00:00:00-04:00  164.649994  165.649994  158.610001  162.550003
2023-04-25 00:00:00-04:00  159.820007  163.470001  158.750000  160.669998
2023-04-26 00:00:00-04:00  160.289993  160.669998  153.139999  153.750000
2023-04-27 00:00:00-04:00  152.639999  160.479996  152.369995  160.190002
2023-04-28 00:00:00-04:00  160.899994  165.000000  157.320007  164.309998

                              Volume  Dividends  Stock Splits
Date
2010-06-29 00:00:00-04:00  281494500        0.0           0.0
2010-06-30 00:00:00-04:00  257806500        0.0           0.0
2010-07-01 00:00:00-04:00  123282000        0.0           0.0
2010-07-02 00:00:00-04:00   77097000        0.0           0.0
2010-07-06 00:00:00-04:00  103003500        0.0           0.0
...                              ...        ...           ...
2023-04-24 00:00:00-04:00  140006600        0.0           0.0
2023-04-25 00:00:00-04:00  121999300        0.0           0.0
2023-04-26 00:00:00-04:00  153364100        0.0           0.0
2023-04-27 00:00:00-04:00  127015200        0.0           0.0
2023-04-28 00:00:00-04:00  122515800        0.0           0.0

[3231 rows x 7 columns]

In [75]:
tesla_highest=max(tesla_history['High'])
tesla_lowest=min(tesla_history['Low'])
tesla_mdd=(tesla_highest-tesla_lowest)*100/tesla_highest
print(tesla_mdd)

tesla_CR=(tesla_history["Open"][-1]-tesla_history["Open"][0])*100/tesla_history["Open"][0]
print(tesla_CR)

tesla_history["return"]=tesla_history["Close"]-tesla_history["Open"]
tesla_avgreturn=stat.mean(tesla_history["return"])
tesla_riskfree=((tesla_history["Open"][0])*(1+5.25/100)**(4869/365)-tesla_history["Open"][0])/4869
tesla_std=stat.stdev(tesla_history["return"])
tesla_sharpe=(tesla_avgreturn-tesla_riskfree)*(252**0.5)/tesla_std
print(tesla_sharpe)

a=[]
i=0
while(tesla_history["return"][i]):
    if(tesla_history["return"][i]<0):
        a.append(tesla_history["return"][i])
    i+=1
    
tesla_downdev=stat.stdev(a)

tesla_sortino=(tesla_avgreturn-tesla_riskfree)*(252**0.5)/tesla_downdev
print(tesla_sortino)

tesla_volatility=stat.stdev(tesla_history["return"]*(252**0.5))
print(tesla_volatility)

99.75906513480815
12602.627670056005
-0.14293543750684484
-8.899788483745423
61.468195030113264

In [76]:
msft=yf.Ticker('msft')
msft_history=msft.history(start='2010-01-01',end='2023-05-01',interval='1d')
msft_history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-01-04 00:00:00-05:00,23.372017,23.738397,23.349118,23.623903,38409100,0.0,0.0
2010-01-05 00:00:00-05:00,23.547571,23.738395,23.387279,23.631533,49749600,0.0,0.0
2010-01-06 00:00:00-05:00,23.570469,23.723128,23.295684,23.486507,58182400,0.0,0.0
2010-01-07 00:00:00-05:00,23.379640,23.433072,23.043792,23.242249,50559700,0.0,0.0
2010-01-08 00:00:00-05:00,23.112492,23.570466,23.081959,23.402542,51197400,0.0,0.0
...,...,...,...,...,...,...,...
2023-04-24 00:00:00-04:00,282.089996,284.950012,278.720001,281.769989,26611000,0.0,0.0
2023-04-25 00:00:00-04:00,279.510010,281.600006,275.369995,275.420013,45772200,0.0,0.0
2023-04-26 00:00:00-04:00,296.700012,299.570007,292.730011,295.369995,64599200,0.0,0.0
2023-04-27 00:00:00-04:00,295.970001,305.200012,295.250000,304.829987,46462600,0.0,0.0
2023-04-28 00:00:00-04:00,304.010010,308.929993,303.309998,307.260010,36446700,0.0,0.0

In [77]:
msft_highest=max(msft_history['High'])
msft_lowest=min(msft_history['Low'])
msft_mdd=(msft_highest-msft_lowest)*100/msft_highest
print(msft_mdd)

msft_CR=(msft_history["Open"][-1]-msft_history["Open"][0])*100/msft_history["Open"][0]
print(msft_CR)

msft_history["return"]=msft_history["Close"]-msft_history["Open"]
msft_avgreturn=stat.mean(msft_history["return"])
msft_riskfree=((msft_history["Open"][0])*(1+5.25/100)**(4869/365)-msft_history["Open"][0])/4869
msft_std=stat.stdev(msft_history["return"])
msft_sharpe=(msft_avgreturn-msft_riskfree)*(252**0.5)/msft_std
print(msft_sharpe)

a=[]
i=0
while(msft_history["return"][i]):
    if(msft_history["return"][i]<0):
        a.append(msft_history["return"][i])
    i+=1
    
msft_downdev=stat.stdev(a)

msft_sortino=(msft_avgreturn-msft_riskfree)*(252**0.5)/msft_downdev
print(msft_sortino)

msft_volatility=stat.stdev(msft_history["return"]*(252**0.5))
print(msft_volatility)

94.93300756818833
1200.7435868315558
0.24960512682478403
1.767680216399321
31.436493170933154

In [78]:
google=yf.Ticker('googl')
google_history=google.history(start='2010-01-01',end='2023-05-01',interval='1d')
google_history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-01-04 00:00:00-05:00,15.689439,15.753504,15.621622,15.684434,78169752,0.0,0.0
2010-01-05 00:00:00-05:00,15.695195,15.711712,15.554054,15.615365,120067812,0.0,0.0
2010-01-06 00:00:00-05:00,15.662162,15.662162,15.174174,15.221722,158988852,0.0,0.0
2010-01-07 00:00:00-05:00,15.250250,15.265265,14.831081,14.867367,256315428,0.0,0.0
2010-01-08 00:00:00-05:00,14.814815,15.096346,14.742492,15.065566,188783028,0.0,0.0
...,...,...,...,...,...,...,...
2023-04-24 00:00:00-04:00,105.489998,106.629997,104.699997,105.970001,23542800,0.0,0.0
2023-04-25 00:00:00-04:00,105.830002,106.690002,103.839996,103.849998,46664100,0.0,0.0
2023-04-26 00:00:00-04:00,104.919998,106.349998,102.629997,103.709999,53347600,0.0,0.0
2023-04-27 00:00:00-04:00,104.449997,108.370003,103.540001,107.589996,50089200,0.0,0.0
2023-04-28 00:00:00-04:00,107.040001,107.349998,105.089996,107.339996,36139800,0.0,0.0

In [79]:
google_highest=max(google_history['High'])
google_lowest=min(google_history['Low'])
google_mdd=(google_highest-google_lowest)*100/google_highest
print(google_mdd)

google_CR=(google_history["Open"][-1]-google_history["Open"][0])*100/google_history["Open"][0]
print(google_CR)

google_history["return"]=google_history["Close"]-google_history["Open"]
google_avgreturn=stat.mean(google_history["return"])
google_riskfree=((google_history["Open"][0])*(1+5.25/100)**(4869/365)-google_history["Open"][0])/4869
google_std=stat.stdev(google_history["return"])
google_sharpe=(google_avgreturn-google_riskfree)*(252**0.5)/google_std
print(google_sharpe)

a=[]
i=0
while(google_history["return"][i]):
    if(google_history["return"][i]<0):
        a.append(google_history["return"][i])
    i+=1
    
google_downdev=stat.stdev(a)

google_sortino=(google_avgreturn-google_riskfree)*(252**0.5)/google_downdev
print(google_sortino)

google_volatility=stat.stdev(google_history["return"]*(252**0.5))
print(google_volatility)

92.83942416095611
582.2423806507452
0.11430772171856658
0.8552522279256192
14.515451409628199

In [83]:
jpm=yf.Ticker('jpm')
jpm_history=jpm.history(start='2010-01-01',end='2023-05-01',interval='1d')
jpm_history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-01-04 00:00:00-05:00,29.530567,30.378538,29.445768,30.279606,35460500,0.05,0.0
2010-01-05 00:00:00-05:00,30.237207,30.979180,30.230139,30.866117,41208300,0.00,0.0
2010-01-06 00:00:00-05:00,30.703597,31.155848,30.604668,31.035717,27729000,0.00,0.0
2010-01-07 00:00:00-05:00,30.943842,31.883674,30.816647,31.650484,44864700,0.00,0.0
2010-01-08 00:00:00-05:00,31.353700,31.586893,31.148776,31.572760,33110100,0.00,0.0
...,...,...,...,...,...,...,...
2023-04-24 00:00:00-04:00,140.460007,141.100006,140.039993,140.729996,7567500,0.00,0.0
2023-04-25 00:00:00-04:00,139.600006,139.960007,137.630005,137.669998,10629300,0.00,0.0
2023-04-26 00:00:00-04:00,137.619995,137.809998,134.000000,135.229996,14416100,0.00,0.0
2023-04-27 00:00:00-04:00,136.000000,137.910004,135.660004,137.050003,9041100,0.00,0.0
2023-04-28 00:00:00-04:00,136.559998,138.320007,135.669998,138.240005,9881800,0.00,0.0

In [84]:
jpm_highest=max(jpm_history['High'])
jpm_lowest=min(jpm_history['Low'])
jpm_mdd=(jpm_highest-jpm_lowest)*100/jpm_highest
print(jpm_mdd)

jpm_CR=(jpm_history["Open"][-1]-jpm_history["Open"][0])*100/jpm_history["Open"][0]
print(jpm_CR)

jpm_history["return"]=jpm_history["Close"]-jpm_history["Open"]
jpm_avgreturn=stat.mean(jpm_history["return"])
jpm_riskfree=((jpm_history["Open"][0])*(1+5.25/100)**(4869/365)-jpm_history["Open"][0])/4869
jpm_std=stat.stdev(jpm_history["return"])
jpm_sharpe=(jpm_avgreturn-jpm_riskfree)*(252**0.5)/jpm_std
print(jpm_sharpe)

a=[]
i=0
while(jpm_history["return"][i]):
    if(jpm_history["return"][i]<0):
        a.append(jpm_history["return"][i])
    i+=1
    
jpm_downdev=stat.stdev(a)

jpm_sortino=(jpm_avgreturn-jpm_riskfree)*(252**0.5)/jpm_downdev
print(jpm_sortino)

jpm_volatility=stat.stdev(jpm_history["return"]*(252**0.5))
print(jpm_volatility)

87.77866305752433
362.43608162500624
-0.06471376037147668
-0.16655634193268815
16.40801273406269

In [39]:
gspc=yf.Ticker('^N225')
gspc_history=gspc.history(start='2010-01-01',end='2023-05-01',interval='1d')
gspc_history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-01-04 00:00:00+09:00,10609.339844,10694.490234,10608.139648,10654.790039,104400000,0.0,0.0
2010-01-05 00:00:00+09:00,10719.440430,10791.040039,10655.570312,10681.830078,166200000,0.0,0.0
2010-01-06 00:00:00+09:00,10709.549805,10768.610352,10661.169922,10731.450195,181800000,0.0,0.0
2010-01-07 00:00:00+09:00,10742.750000,10774.000000,10636.669922,10681.660156,182600000,0.0,0.0
2010-01-08 00:00:00+09:00,10743.299805,10816.450195,10677.559570,10798.320312,211800000,0.0,0.0
...,...,...,...,...,...,...,...
2023-04-24 00:00:00+09:00,28631.779297,28680.650391,28567.240234,28593.519531,50000000,0.0,0.0
2023-04-25 00:00:00+09:00,28697.730469,28806.689453,28609.769531,28620.070312,59300000,0.0,0.0
2023-04-26 00:00:00+09:00,28478.519531,28551.609375,28319.769531,28416.470703,68700000,0.0,0.0
2023-04-27 00:00:00+09:00,28340.589844,28459.730469,28241.669922,28457.679688,73600000,0.0,0.0
2023-04-28 00:00:00+09:00,28705.910156,28879.240234,28499.509766,28856.439453,104000000,0.0,0.0

In [40]:
indices=['^GSPC','^DJI','^N100','^FTSE','^N225']
for x in indices:
    index=yf.Ticker(x)
    index_history=index.history(start='2010-01-01',end='2023-05-01',interval='1d')
    index_highest=max(index_history['High'])
    index_lowest=min(index_history['Low'])
    index_mdd=(index_highest-index_lowest)*100/index_highest
    print(index_mdd)

    index_CR=(index_history["Open"][-1]-index_history["Open"][0])*100/index_history["Open"][0]
    print(index_CR)

    index_history["return"]=index_history["Close"]-index_history["Open"]
    index_avgreturn=stat.mean(index_history["return"])
    index_riskfree=((index_history["Open"][0])*(1+5.25/100)**(4869/365)-index_history["Open"][0])/4869
    index_std=stat.stdev(index_history["return"])
    index_sharpe=(index_avgreturn-index_riskfree)*(252**0.5)/index_std
    print(index_sharpe)

    a=[]
    i=0
    while(index_history["return"][i]):
        if(index_history["return"][i]<0):
            a.append(index_history["return"][i])
        i+=1
    
    index_downdev=stat.stdev(a)

    index_sortino=(index_avgreturn-index_riskfree)*(252**0.5)/index_downdev
    print(index_sortino)

    index_volatility=stat.stdev(index_history["return"]*(252**0.5))
    print(index_volatility)
    print('\n')

79.02075804775056
269.8529112722836
0.16985781458393825
0.4450944439707104
388.2836865395172


73.98205346834283
224.01910415543375
0.1748824005203124
0.45462541196767475
3160.480851209855


63.05088570283293
99.47258837901714
-0.24375822087445298
-0.38157142018696516
128.28663301587855


40.475451505877174
44.684000054485004
-0.09304928031604351
-0.13648360025710837
1019.4402086320539


73.58147699191987
170.57206743321314
-0.369150341043039
-0.4991219765884245
2635.6724328876976